services:
  db:
    image: postgres:15
    container_name: senate_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: senate
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
